/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgendaCategory = { 'workshop' : null } |
  { 'meeting' : null } |
  { 'general' : null } |
  { 'training' : null };
export type ExternalBlob = Uint8Array;
export interface Kpi {
  'id' : bigint,
  'status' : KpiStatus,
  'period' : KpiPeriod,
  'relatedProgramId' : bigint,
  'name' : string,
  'team' : PersonInCharge,
  'deadline' : [] | [bigint],
  'realizationValue' : bigint,
  'targetValue' : bigint,
}
export type KpiPeriod = { 'annual' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null };
export type KpiStatus = { 'achieved' : null } |
  { 'notAchieved' : null } |
  { 'inProgress' : null };
export interface PersonInCharge {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'division' : string,
}
export interface Program {
  'id' : bigint,
  'status' : ProgramStatus,
  'endDate' : bigint,
  'name' : string,
  'unit' : string,
  'description' : string,
  'progress' : bigint,
  'priority' : ProgramPriority,
  'personInCharge' : PersonInCharge,
  'startDate' : bigint,
}
export type ProgramPriority = { 'low' : null } |
  { 'high' : null } |
  { 'middle' : null };
export type ProgramStatus = { 'completed' : null } |
  { 'ongoing' : null } |
  { 'planning' : null };
export interface TeamAgendaItem {
  'id' : bigint,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'description' : string,
  'attendees' : Array<string>,
  'category' : AgendaCategory,
}
export interface TeamMemberCreateRequest {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'division' : string,
  'managerId' : [] | [bigint],
}
export interface TeamMemberWithAvatar {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'division' : string,
  'managerId' : [] | [bigint],
  'avatar' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface TimeRange { 'end' : Time, 'start' : Time }
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'admin' : null } |
  { 'viewer' : null } |
  { 'coordinator' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'calculateKpiProgress' : ActorMethod<[bigint], [] | [bigint]>,
  'calculateProgramProgress' : ActorMethod<[bigint], [] | [bigint]>,
  'createKpi' : ActorMethod<[Kpi], bigint>,
  'createProgram' : ActorMethod<[Program], bigint>,
  'createTeamAgendaItem' : ActorMethod<[TeamAgendaItem], bigint>,
  'createTeamMember' : ActorMethod<[TeamMemberCreateRequest], undefined>,
  'deleteKpi' : ActorMethod<[bigint], undefined>,
  'deleteProgram' : ActorMethod<[bigint], undefined>,
  'deleteTeamAgendaItem' : ActorMethod<[bigint], undefined>,
  'deleteTeamMember' : ActorMethod<[bigint], undefined>,
  'getAllKPIs' : ActorMethod<[], Array<Kpi>>,
  'getAllPrograms' : ActorMethod<[], Array<Program>>,
  'getAllTeamAgendaItems' : ActorMethod<[], Array<TeamAgendaItem>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMemberWithAvatar>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getFilteredKpis' : ActorMethod<[KpiStatus, KpiPeriod], Array<Kpi>>,
  'getFilteredPrograms' : ActorMethod<[ProgramStatus], Array<Program>>,
  'getKPIsByIds' : ActorMethod<[Array<bigint>], Array<Kpi>>,
  'getKPIsByName' : ActorMethod<[string], Array<Kpi>>,
  'getKPIsByProgramIds' : ActorMethod<[Array<bigint>], Array<Kpi>>,
  'getKPIsByTeam' : ActorMethod<[string], Array<Kpi>>,
  'getKPIsByTeamPIC' : ActorMethod<[string], Array<Kpi>>,
  'getKpi' : ActorMethod<[bigint], [] | [Kpi]>,
  'getPagedKpis' : ActorMethod<[bigint, bigint], Array<Kpi>>,
  'getPagedPrograms' : ActorMethod<[bigint, bigint], Array<Program>>,
  'getProgram' : ActorMethod<[bigint], [] | [Program]>,
  'getProgramsActiveInRange' : ActorMethod<[TimeRange], Array<Program>>,
  'getProgramsByDivision' : ActorMethod<[string], Array<Program>>,
  'getProgramsByDivisionAndPriority' : ActorMethod<
    [string, ProgramPriority],
    Array<Program>
  >,
  'getProgramsByIds' : ActorMethod<[Array<bigint>], Array<Program>>,
  'getProgramsByName' : ActorMethod<[string], Array<Program>>,
  'getProgramsByStatus' : ActorMethod<[ProgramStatus], Array<Program>>,
  'getProgramsByTeam' : ActorMethod<[string], Array<Program>>,
  'getTeamAgendaItemsByRange' : ActorMethod<[TimeRange], Array<TeamAgendaItem>>,
  'getTeamMemberAvatar' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'getTeamMembersByDivision' : ActorMethod<
    [string],
    Array<TeamMemberWithAvatar>
  >,
  'getTeamMembersByDivisionFiltered' : ActorMethod<
    [string],
    Array<TeamMemberWithAvatar>
  >,
  'getUniqueDivisions' : ActorMethod<[], Array<string>>,
  'getUniquePICNames' : ActorMethod<[], Array<string>>,
  'getUniquePriorities' : ActorMethod<[], Array<ProgramPriority>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTeamMemberAvatar' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'updateKpi' : ActorMethod<[bigint, Kpi], undefined>,
  'updateKpiAndSyncProgram' : ActorMethod<[bigint, Kpi], undefined>,
  'updateProgram' : ActorMethod<[bigint, Program], undefined>,
  'updateTeamAgendaItem' : ActorMethod<[bigint, TeamAgendaItem], undefined>,
  'updateTeamMember' : ActorMethod<
    [bigint, TeamMemberCreateRequest],
    undefined
  >,
  'updateUserProfileRole' : ActorMethod<[Principal, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];