/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const KpiStatus = IDL.Variant({
  'achieved' : IDL.Null,
  'notAchieved' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const KpiPeriod = IDL.Variant({
  'annual' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
});
export const PersonInCharge = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'division' : IDL.Text,
});
export const Kpi = IDL.Record({
  'id' : IDL.Nat,
  'status' : KpiStatus,
  'period' : KpiPeriod,
  'relatedProgramId' : IDL.Nat,
  'name' : IDL.Text,
  'team' : PersonInCharge,
  'deadline' : IDL.Opt(IDL.Int),
  'realizationValue' : IDL.Nat,
  'targetValue' : IDL.Nat,
});
export const ProgramStatus = IDL.Variant({
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
  'planning' : IDL.Null,
});
export const ProgramPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'middle' : IDL.Null,
});
export const Program = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProgramStatus,
  'endDate' : IDL.Int,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'priority' : ProgramPriority,
  'personInCharge' : PersonInCharge,
  'startDate' : IDL.Int,
});
export const AgendaCategory = IDL.Variant({
  'workshop' : IDL.Null,
  'meeting' : IDL.Null,
  'general' : IDL.Null,
  'training' : IDL.Null,
});
export const TeamAgendaItem = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'description' : IDL.Text,
  'attendees' : IDL.Vec(IDL.Text),
  'category' : AgendaCategory,
});
export const TeamMemberCreateRequest = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'division' : IDL.Text,
  'managerId' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TeamMemberWithAvatar = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'division' : IDL.Text,
  'managerId' : IDL.Opt(IDL.Nat),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'viewer' : IDL.Null,
  'coordinator' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const Time = IDL.Int;
export const TimeRange = IDL.Record({ 'end' : Time, 'start' : Time });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'calculateKpiProgress' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'calculateProgramProgress' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'createKpi' : IDL.Func([Kpi], [IDL.Nat], []),
  'createProgram' : IDL.Func([Program], [IDL.Nat], []),
  'createTeamAgendaItem' : IDL.Func([TeamAgendaItem], [IDL.Nat], []),
  'createTeamMember' : IDL.Func([TeamMemberCreateRequest], [], []),
  'deleteKpi' : IDL.Func([IDL.Nat], [], []),
  'deleteProgram' : IDL.Func([IDL.Nat], [], []),
  'deleteTeamAgendaItem' : IDL.Func([IDL.Nat], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
  'getAllKPIs' : IDL.Func([], [IDL.Vec(Kpi)], ['query']),
  'getAllPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
  'getAllTeamAgendaItems' : IDL.Func([], [IDL.Vec(TeamAgendaItem)], ['query']),
  'getAllTeamMembers' : IDL.Func(
      [],
      [IDL.Vec(TeamMemberWithAvatar)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getFilteredKpis' : IDL.Func(
      [KpiStatus, KpiPeriod],
      [IDL.Vec(Kpi)],
      ['query'],
    ),
  'getFilteredPrograms' : IDL.Func(
      [ProgramStatus],
      [IDL.Vec(Program)],
      ['query'],
    ),
  'getKPIsByIds' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(Kpi)], ['query']),
  'getKPIsByName' : IDL.Func([IDL.Text], [IDL.Vec(Kpi)], ['query']),
  'getKPIsByProgramIds' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(Kpi)],
      ['query'],
    ),
  'getKPIsByTeam' : IDL.Func([IDL.Text], [IDL.Vec(Kpi)], ['query']),
  'getKPIsByTeamPIC' : IDL.Func([IDL.Text], [IDL.Vec(Kpi)], ['query']),
  'getKpi' : IDL.Func([IDL.Nat], [IDL.Opt(Kpi)], ['query']),
  'getPagedKpis' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Kpi)], ['query']),
  'getPagedPrograms' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Program)],
      ['query'],
    ),
  'getProgram' : IDL.Func([IDL.Nat], [IDL.Opt(Program)], ['query']),
  'getProgramsActiveInRange' : IDL.Func(
      [TimeRange],
      [IDL.Vec(Program)],
      ['query'],
    ),
  'getProgramsByDivision' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
  'getProgramsByDivisionAndPriority' : IDL.Func(
      [IDL.Text, ProgramPriority],
      [IDL.Vec(Program)],
      ['query'],
    ),
  'getProgramsByIds' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(Program)],
      ['query'],
    ),
  'getProgramsByName' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
  'getProgramsByStatus' : IDL.Func(
      [ProgramStatus],
      [IDL.Vec(Program)],
      ['query'],
    ),
  'getProgramsByTeam' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
  'getTeamAgendaItemsByRange' : IDL.Func(
      [TimeRange],
      [IDL.Vec(TeamAgendaItem)],
      ['query'],
    ),
  'getTeamMemberAvatar' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getTeamMembersByDivision' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TeamMemberWithAvatar)],
      ['query'],
    ),
  'getTeamMembersByDivisionFiltered' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TeamMemberWithAvatar)],
      ['query'],
    ),
  'getUniqueDivisions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUniquePICNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUniquePriorities' : IDL.Func([], [IDL.Vec(ProgramPriority)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTeamMemberAvatar' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'updateKpi' : IDL.Func([IDL.Nat, Kpi], [], []),
  'updateKpiAndSyncProgram' : IDL.Func([IDL.Nat, Kpi], [], []),
  'updateProgram' : IDL.Func([IDL.Nat, Program], [], []),
  'updateTeamAgendaItem' : IDL.Func([IDL.Nat, TeamAgendaItem], [], []),
  'updateTeamMember' : IDL.Func([IDL.Nat, TeamMemberCreateRequest], [], []),
  'updateUserProfileRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const KpiStatus = IDL.Variant({
    'achieved' : IDL.Null,
    'notAchieved' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const KpiPeriod = IDL.Variant({
    'annual' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const PersonInCharge = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'division' : IDL.Text,
  });
  const Kpi = IDL.Record({
    'id' : IDL.Nat,
    'status' : KpiStatus,
    'period' : KpiPeriod,
    'relatedProgramId' : IDL.Nat,
    'name' : IDL.Text,
    'team' : PersonInCharge,
    'deadline' : IDL.Opt(IDL.Int),
    'realizationValue' : IDL.Nat,
    'targetValue' : IDL.Nat,
  });
  const ProgramStatus = IDL.Variant({
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
    'planning' : IDL.Null,
  });
  const ProgramPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'middle' : IDL.Null,
  });
  const Program = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProgramStatus,
    'endDate' : IDL.Int,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'priority' : ProgramPriority,
    'personInCharge' : PersonInCharge,
    'startDate' : IDL.Int,
  });
  const AgendaCategory = IDL.Variant({
    'workshop' : IDL.Null,
    'meeting' : IDL.Null,
    'general' : IDL.Null,
    'training' : IDL.Null,
  });
  const TeamAgendaItem = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'description' : IDL.Text,
    'attendees' : IDL.Vec(IDL.Text),
    'category' : AgendaCategory,
  });
  const TeamMemberCreateRequest = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'division' : IDL.Text,
    'managerId' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TeamMemberWithAvatar = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'division' : IDL.Text,
    'managerId' : IDL.Opt(IDL.Nat),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'viewer' : IDL.Null,
    'coordinator' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const Time = IDL.Int;
  const TimeRange = IDL.Record({ 'end' : Time, 'start' : Time });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'calculateKpiProgress' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'calculateProgramProgress' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'createKpi' : IDL.Func([Kpi], [IDL.Nat], []),
    'createProgram' : IDL.Func([Program], [IDL.Nat], []),
    'createTeamAgendaItem' : IDL.Func([TeamAgendaItem], [IDL.Nat], []),
    'createTeamMember' : IDL.Func([TeamMemberCreateRequest], [], []),
    'deleteKpi' : IDL.Func([IDL.Nat], [], []),
    'deleteProgram' : IDL.Func([IDL.Nat], [], []),
    'deleteTeamAgendaItem' : IDL.Func([IDL.Nat], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
    'getAllKPIs' : IDL.Func([], [IDL.Vec(Kpi)], ['query']),
    'getAllPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
    'getAllTeamAgendaItems' : IDL.Func(
        [],
        [IDL.Vec(TeamAgendaItem)],
        ['query'],
      ),
    'getAllTeamMembers' : IDL.Func(
        [],
        [IDL.Vec(TeamMemberWithAvatar)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getFilteredKpis' : IDL.Func(
        [KpiStatus, KpiPeriod],
        [IDL.Vec(Kpi)],
        ['query'],
      ),
    'getFilteredPrograms' : IDL.Func(
        [ProgramStatus],
        [IDL.Vec(Program)],
        ['query'],
      ),
    'getKPIsByIds' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(Kpi)], ['query']),
    'getKPIsByName' : IDL.Func([IDL.Text], [IDL.Vec(Kpi)], ['query']),
    'getKPIsByProgramIds' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(Kpi)],
        ['query'],
      ),
    'getKPIsByTeam' : IDL.Func([IDL.Text], [IDL.Vec(Kpi)], ['query']),
    'getKPIsByTeamPIC' : IDL.Func([IDL.Text], [IDL.Vec(Kpi)], ['query']),
    'getKpi' : IDL.Func([IDL.Nat], [IDL.Opt(Kpi)], ['query']),
    'getPagedKpis' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Kpi)], ['query']),
    'getPagedPrograms' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Program)],
        ['query'],
      ),
    'getProgram' : IDL.Func([IDL.Nat], [IDL.Opt(Program)], ['query']),
    'getProgramsActiveInRange' : IDL.Func(
        [TimeRange],
        [IDL.Vec(Program)],
        ['query'],
      ),
    'getProgramsByDivision' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Program)],
        ['query'],
      ),
    'getProgramsByDivisionAndPriority' : IDL.Func(
        [IDL.Text, ProgramPriority],
        [IDL.Vec(Program)],
        ['query'],
      ),
    'getProgramsByIds' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(Program)],
        ['query'],
      ),
    'getProgramsByName' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
    'getProgramsByStatus' : IDL.Func(
        [ProgramStatus],
        [IDL.Vec(Program)],
        ['query'],
      ),
    'getProgramsByTeam' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
    'getTeamAgendaItemsByRange' : IDL.Func(
        [TimeRange],
        [IDL.Vec(TeamAgendaItem)],
        ['query'],
      ),
    'getTeamMemberAvatar' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getTeamMembersByDivision' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TeamMemberWithAvatar)],
        ['query'],
      ),
    'getTeamMembersByDivisionFiltered' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TeamMemberWithAvatar)],
        ['query'],
      ),
    'getUniqueDivisions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUniquePICNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUniquePriorities' : IDL.Func([], [IDL.Vec(ProgramPriority)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTeamMemberAvatar' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'updateKpi' : IDL.Func([IDL.Nat, Kpi], [], []),
    'updateKpiAndSyncProgram' : IDL.Func([IDL.Nat, Kpi], [], []),
    'updateProgram' : IDL.Func([IDL.Nat, Program], [], []),
    'updateTeamAgendaItem' : IDL.Func([IDL.Nat, TeamAgendaItem], [], []),
    'updateTeamMember' : IDL.Func([IDL.Nat, TeamMemberCreateRequest], [], []),
    'updateUserProfileRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };